Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Answer = Yes, there is a difference in the data type of the variables list_ and array_list. The variable list_ is a Python list, whereas array_list is a NumPy array

In [12]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [13]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)



In [20]:
print("Data types of elements in list_")
for i in list_:
    print(f" {i}:, Type: {type(i)}")
    
print("Data types od elements in array_list")
for i in array_list:
    print(f"{i}:,Type:{type(i)}")


Data types of elements in list_
 1:, Type: <class 'str'>
 2:, Type: <class 'str'>
 3:, Type: <class 'str'>
 4:, Type: <class 'str'>
 5:, Type: <class 'str'>
Data types od elements in array_list
1:,Type:<class 'numpy.str_'>
2:,Type:<class 'numpy.str_'>
3:,Type:<class 'numpy.str_'>
4:,Type:<class 'numpy.str_'>
5:,Type:<class 'numpy.str_'>


Q3.Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [21]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_, dtype = int)



Answer= Yes, there will be a difference in the data type of the elements present in the variables list_ and array_list because we have specified the dtype of array_list to be int. The elements in list_ are of type str (strings), while the elements in array_list are of type int

In [22]:
print("Data types of elements in list_")
for i in list_:
    print(f" {i}:, Type: {type(i)}")
    
print("Data types od elements in array_list")
for i in array_list:
    print(f"{i}:,Type:{type(i)}")


Data types of elements in list_
 1:, Type: <class 'str'>
 2:, Type: <class 'str'>
 3:, Type: <class 'str'>
 4:, Type: <class 'str'>
 5:, Type: <class 'str'>
Data types od elements in array_list
1:,Type:<class 'numpy.int64'>
2:,Type:<class 'numpy.int64'>
3:,Type:<class 'numpy.int64'>
4:,Type:<class 'numpy.int64'>
5:,Type:<class 'numpy.int64'>


Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape
(ii) size

In [23]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [28]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
num_array.shape

(2, 3)

In [25]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [48]:
data=np.zeros((3,3))

In [49]:
data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [44]:
data1=np.eye(5)

In [45]:
data1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])